name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      uses: docker/login-action@v1
      with:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          
      run:  |
      #  docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      
    - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ github.repository }}:${{ steps.vars.outputs.tag }}
          
    #  -name: build docker image
    #  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)   
    #  -name: Docker Push
     # run: docker push ${{secrets.DOCKER_USER}}/docker-php-5.2
